### ISSUE TITLE
invalid MIME type 'multipart/form-data' in 'consumes

### ISSUE THREAD

**Issue by ellavish89** [sylvainlaurent/swagger-validator-maven-plugin#23]
invalid MIME type 'multipart/form-data' in 'consumes
getting that as part of verify although this is a valid MIME

**Comment by ellavish89** [comment]
and another small question : Can I set "SemanticErrors" not to fail on errors, but DefenitionSemanticErrors to fail?

Thanks a lot

**Comment by ellavish89** [comment]
Thanks,
will there be a new version release for that soon?

**Comment by giuliopulina** [comment]
@ellavish89 hopefully yes, though it depends when the [pull request](https://github.com/sylvainlaurent/swagger-validator-maven-plugin/pull/25) will be merged.
In the meantime, can you give [my branch](https://github.com/giuliopulina/swagger-validator-maven-plugin/tree/bugfix/Issue-21_external_ref_with_no_dot_not_working) a try and verify that the issue described here is fixed?

**Comment by giuliopulina** [comment]
> and another small question : Can I set "SemanticErrors" not to fail on errors, but DefenitionSemanticErrors to fail?
> 
> Thanks a lot

@ellavish89 about your question, currently this kind of granularity in behavior is not supported.
Personally I think that the spec, as a whole, is either valid or not valid: in the latter case, the only available options should be to fail or just raise warning messages.

**Comment by ellavish89** [comment]
Thanks for the answer. I will check now and update

**Comment by warden** [comment]
I am still getting the failures below with the SNAPSHOT from branch you mentioned above:

```
[ERROR] SemanticError  'consumes' cannot be empty
[ERROR] SemanticError  'consumes' must be equal to 'consumes: []'
[ERROR] SemanticError  'produces' cannot be empty
[ERROR] SemanticError invalid MIME type 'multipart/form-data' in 'consumes'

[ERROR] Failed to execute goal com.github.sylvainlaurent.maven:swagger-validator-maven-plugin:1.2.7-SNAPSHOT:validate (validate) on project test: Some files are not valid, see previous logs. Encountered 139 errors. -> [Help 1]
```
